# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'
require 'bubble-wrap/location'
require 'bubble-wrap/core'

require 'bundler'
Bundler.require

Motion::Project::App.setup do |app|
  app.name = 'location'
end
