# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'
require 'bubble-wrap/location'
require 'bubble-wrap/http'
require 'bubble-wrap/core'

Motion::Project::App.setup do |app|
  app.name = 'location'
end
