# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'

$:.unshift("../../lib")
require 'bubble-wrap/media'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'media'
end
