# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'
require 'bubble-wrap/core'
require 'bubble-wrap/camera'

Motion::Project::App.setup do |app|
  app.name = 'camera'
end
