require "bubble-wrap/version" unless defined?(BubbleWrap::VERSION)
require File.expand_path('../bubble-wrap/loader', __FILE__)
require File.expand_path('../bubble-wrap/core', __FILE__)
require File.expand_path('../bubble-wrap/http', __FILE__)
require File.expand_path('../bubble-wrap/dispatch', __FILE__)
