# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'
require 'bundler'
Bundler.require :default

Motion::Project::App.setup do |app|
  app.name = 'gesture'
end
